USE master
GO

IF db_id('ANIMABD') is not null
begin
	ALTER DATABASE ANIMABD
	SET SINGLE_USER WITH ROLLBACK IMMEDIATE

	DROP DATABASE ANIMABD
end
go

select * from sys.tables
go

CREATE DATABASE ANIMABD
COLLATE Modern_Spanish_CI_AI
GO

USE ANIMABD
GO

--TABLA DE ROLES DE USUARIO DONDE PUEDE SER "ADMINISTRADOR" O "CLIENTE"
CREATE TABLE ROLES
(
COD_ROLES INT IDENTITY PRIMARY KEY,
NOMBRE_ROLES VARCHAR(20) NOT NULL,
)
GO

--TABLA DE EMPLEADOS LOS CUALES GENERARAN LAS VENTAS
CREATE TABLE EMPLEADOS
(
COD_EMPLEADOS CHAR(7) PRIMARY KEY, --EMP0001
NOMBRES VARCHAR(100) NOT NULL,
APELLIDOS VARCHAR(100) NOT NULL,
DNI CHAR(8) NOT NULL,
FEC_NAC DATE NOT NULL,
ELIMINADO CHAR(2) DEFAULT 'No'
)
GO

--TABLA DE USUARIO Y CONTRASE�A
CREATE TABLE USUARIO
(
COD_USUARIO INT IDENTITY PRIMARY KEY,
USUARIO VARCHAR(255) NOT NULL,
CLAVE VARCHAR(255) NOT NULL,
CODROL INT NOT NULL,
CODEMPLEADO CHAR(7) NOT NULL,
ELIMINADO CHAR(2) DEFAULT 'No'
CONSTRAINT FKCODROL FOREIGN KEY (CODROL) REFERENCES ROLES(COD_ROLES),
CONSTRAINT FKCODEMPLEADO FOREIGN KEY (CODEMPLEADO) REFERENCES EMPLEADOS(COD_EMPLEADOS)
)
GO



--AQUI SE REGISTRARAN LAS ESPECIALIDADES DE CADA CONSULTOR EL CUAL
-- ASESORARA A LA PERSONA A QUE COMIDA DEBE DE ELEGIR
CREATE TABLE ESPECIALIDAD
(
COD_ESPECIALIDAD INT IDENTITY PRIMARY KEY,
NOM_ESPECIALIDAD VARCHAR(50) NOT NULL
)
GO

--AQUI SE REGISTRARAN A LOS CONSULTORES CON SUS RESPECTIVOS DATOS
CREATE TABLE CONSULTORES
(
COD_CONSULTORES CHAR(7) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
DNI CHAR(8) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
CODESPECIALIDAD INT,
ELIMINADO CHAR(2) DEFAULT 'No'
CONSTRAINT FKCODESPECIALIDAD FOREIGN KEY (CODESPECIALIDAD) REFERENCES ESPECIALIDAD(COD_ESPECIALIDAD)
)
GO

--AQUI DECLARAREMOS EL TIPO DE CLIENTE SI ES PERSONA NATURAL O EMPRESA
CREATE TABLE TIPO_CLIENTE
(
COD_TIPOCLI INT IDENTITY PRIMARY KEY,
NOM_TIPOCLI VARCHAR(30) -- PERSONA NATURAL O EMPRESA
)
GO

--TABLA DE CLIENTES EN GENERAL (PERSONA NATURAL O EMPRESA)
CREATE TABLE CLIENTE
(
COD_CLIENTE CHAR(8) PRIMARY KEY, -- CLI00001
NOMBRES_COMPLETOS VARCHAR(100) NOT NULL,
DNIRUC VARCHAR(11) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
TIPOCLI INT NOT NULL,
ELIMINADO CHAR(2) DEFAULT 'No'
CONSTRAINT FKTIPOCLI FOREIGN KEY (TIPOCLI) REFERENCES TIPO_CLIENTE(COD_TIPOCLI)
)
GO

--TABLA DE ANIMALES DONDE SE REGISTRARAN TODOS LOS TIPOS DE ANIMALES QUE EXISTEN YA SEA
-- PATO(JERSON), POLLO, VACA, TORO, PAVO, LECHON, CABALLO, YEGUA, ETC ETC ETC
CREATE TABLE ANIMALES
(
COD_ANIMAL INT IDENTITY PRIMARY KEY,
NOM_ANIMAL VARCHAR(50)
)
GO

--TABLA TIPO DONDE SE REGISTRARA DE QUE TIPO ES EL PRODUCTO, SI ES COMIDA BALANCEADA O VITAMINAS
CREATE TABLE TIPO_PRODUCTO
(
COD_TIPO INT IDENTITY PRIMARY KEY,
NOM_TIPO VARCHAR(50)
)
GO


--TABLA PRODUCTOS DONDE SE REGISTRARA EL CODIGO DEL PRODUCTO, SU DESCRIPCION, EL STOCK DISPONIBLE Y LA DISPONIBILIDAD (ESTO VARIA POR STOCK DEL PRODUCTO)
-- ANIMAL DONDE SE VERA PARA QUE ANIMAL CORRESPONDE EL PRODUCTO, EL TIPO DE COMIDA DONDE SE VISUALIZARA SI SON VITAMINAS O COMIDA BALANCEADA
CREATE TABLE PRODUCTOS
(
CODIGO CHAR(7) PRIMARY KEY, --PR00001
DESCRIPCION VARCHAR(50) NOT NULL,
PRECIO DECIMAL(10, 2) NOT NULL,
STOCK INT NOT NULL,
ANIMAL INT NOT NULL,
TIPOCOMI INT NOT NULL,
ELIMINADO CHAR(2) DEFAULT 'No',
CONSTRAINT FKANIMAL FOREIGN KEY (ANIMAL) REFERENCES ANIMALES(COD_ANIMAL),
CONSTRAINT FKTIPO FOREIGN KEY (TIPOCOMI) REFERENCES TIPO_PRODUCTO(COD_TIPO)
)
GO

--TABLA DE TIPO VENTA DONDE SE DIFERENCIARA SI ES 'BOLETA' O 'FACTURA'
CREATE TABLE TIPO_VENTA
(
	CODIGO_TVEN INT IDENTITY PRIMARY KEY,
	NOMBRE_TVEN VARCHAR(20)
)
go

--TABLA DE BOLETA DE VENTA DONDE SE REGISTRARA 
CREATE TABLE BOL_VENTA
(
CODIGO_VENTA CHAR(7) PRIMARY KEY, --VET0001
FEC_VENTA DATE NOT NULL,
TIPO_VEN INT NOT NULL,
COD_CLIENTE CHAR(8) NOT NULL,
COD_EMPLEADO CHAR(7) NOT NULL,
COD_CONSULTORES CHAR(7) NOT NULL,
TOTAL DECIMAL(10,2),
ANULADO CHAR(2) DEFAULT 'No',
CONSTRAINT FKTIPOVENT FOREIGN KEY (TIPO_VEN) REFERENCES TIPO_VENTA(CODIGO_TVEN),
CONSTRAINT FKCODCLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
CONSTRAINT FKCODEMPLEADOS FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADOS(COD_EMPLEADOS),
CONSTRAINT FKCODCONSULTORES FOREIGN KEY (COD_CONSULTORES) REFERENCES CONSULTORES(COD_CONSULTORES)
)
GO

CREATE TABLE DET_VENTA
(
CODVEN CHAR(7) NOT NULL, --DET0001
CODPROD CHAR(7) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO DECIMAL(10,2) NOT NULL,
CONSTRAINT FKCODVENTA FOREIGN KEY (CODVEN) REFERENCES BOL_VENTA(CODIGO_VENTA),
CONSTRAINT FKCODPRODUCTO FOREIGN KEY (CODPROD) REFERENCES PRODUCTOS(CODIGO)
)
GO

select *from dbo.BOL_VENTA
go
