/* ZONA DE LOS PROCEDURES */

USE ANIMABD
GO

SELECT * FROM sys.tables
GO

/* INICIO DE GESTION DE USUARIO */
CREATE OR ALTER PROCEDURE SP_LISTAR_ROLES
AS
	SELECT *
	FROM ROLES
GO

--
CREATE OR ALTER PROCEDURE SP_REGISTRAR_EMPLEADO
(
@NOM VARCHAR(100),
@APE VARCHAR(100),
@DNI CHAR(8),
@FN DATE
)
AS
	DECLARE @CODIGO CHAR(7);
	SET @CODIGO = 'EMP' + RIGHT('0000' + CAST(ISNULL((SELECT MAX(RIGHT(COD_EMPLEADOS, 4)) FROM EMPLEADOS), 0) +1 AS VARCHAR(4)), 4);

	INSERT INTO EMPLEADOS VALUES (@CODIGO, @NOM, @APE, @DNI, @FN, 'No')
GO

EXEC SP_REGISTRAR_EMPLEADO 'Marco','Gutierrez','74878420','19991220'
GO
--
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_EMPLEADO
(
@NOM VARCHAR(100),
@APE VARCHAR(100),
@DNI CHAR(8),
@FN DATE,
@COD CHAR(7)
)
AS
	UPDATE EMPLEADOS SET NOMBRES = @NOM, APELLIDOS = @APE, DNI = @DNI, FEC_NAC = @FN WHERE COD_EMPLEADOS = @COD
GO
--
CREATE OR ALTER PROCEDURE SP_LISTAR_EMPLEADO
AS
	SELECT *
	FROM EMPLEADOS
	WHERE ELIMINADO = 'No'
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_EMPLEADO_FILTRO
(@dato varchar(100))
AS
	SELECT *
	FROM EMPLEADOS
	WHERE (NOMBRES LIKE CONCAT(@dato,'%') OR APELLIDOS LIKE CONCAT(@dato,'%') OR DNI LIKE CONCAT(@dato,'%')) AND ELIMINADO = 'No'
GO
--
CREATE OR ALTER PROCEDURE SP_ELIMINAR_EMPLEADO
(
@COD CHAR(7)
)
AS
	UPDATE EMPLEADOS SET ELIMINADO = 'Si' WHERE COD_EMPLEADOS = @COD
GO
--
CREATE OR ALTER PROCEDURE SP_LISTAR_USUARIO
AS
	SELECT *
	FROM USUARIO
	WHERE ELIMINADO = 'No'
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_USUARIO_FILTRO
(@usuario varchar(50))
AS
	SELECT *
	FROM USUARIO
	WHERE USUARIO LIKE CONCAT(@usuario,'%') AND ELIMINADO = 'No'
GO

EXEC SP_LISTAR_USUARIO
GO
--
CREATE OR ALTER PROCEDURE SP_REGISTRAR_USUARIO
(
@USU VARCHAR(255),
@CLAVE VARCHAR(255),
@CODROL INT,
@CODEMPLE CHAR(7)
)
AS
	INSERT INTO USUARIO VALUES (@USU, @CLAVE, @CODROL, @CODEMPLE, 'No')
GO
--
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_USUARIO
(
@USU VARCHAR(255),
@CLAVE VARCHAR(255),
@CODROL INT,
@CODEMPLE CHAR(7),
@CODUSU INT
)
AS
	UPDATE USUARIO SET USUARIO = @USU, CLAVE = @CLAVE, CODROL = @CODROL, CODEMPLEADO = @CODEMPLE WHERE COD_USUARIO = @CODUSU
GO

CREATE OR ALTER PROCEDURE SP_ELIMINAR_USUARIO
(
@CODUSU INT
)
AS
	UPDATE USUARIO SET ELIMINADO = 'Si' WHERE COD_USUARIO = @CODUSU
GO

/* FIN DE LOS PROCEDIMIENTOS DE GESTION DE USUARIO Y EMPLEADO */

/* COMIENZO DE LOS PROCEDIMIENTOS DE GESTION A LOS CONSULTORES Y SUS ESPECIALIDADES */

CREATE OR ALTER PROCEDURE SP_LISTAR_ESPECIALIDAD
AS
	SELECT *
	FROM ESPECIALIDAD
GO

CREATE OR ALTER PROCEDURE SP_REGISTRAR_CONSULTOR
(
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@DNI CHAR(8),
@CORREO VARCHAR(50),
@CODESPECIALIDAD INT
)
AS
	DECLARE @CODCONSUL CHAR(7);
	SET @CODCONSUL = 'CON' + RIGHT('0000' + CAST(ISNULL((SELECT MAX(RIGHT(COD_CONSULTORES,4)) FROM CONSULTORES), 0) + 1 AS VARCHAR(4)), 4);

	INSERT INTO CONSULTORES VALUES (@CODCONSUL, @NOMBRE, @APELLIDO, @DNI, @CORREO, @CODESPECIALIDAD, 'No');
GO

EXEC SP_REGISTRAR_CONSULTOR 'Mario','Jimenez','7774444','mariojimenez@gmail.com',1
GO

CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_CONSULTOR
(
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@DNI CHAR(8),
@CORREO VARCHAR(50),
@CODESPECIALIDAD INT,
@CODCONSUL CHAR(7)
)
AS
	UPDATE CONSULTORES SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, DNI = @DNI, CORREO = @CORREO, CODESPECIALIDAD = @CODESPECIALIDAD WHERE COD_CONSULTORES = @CODCONSUL
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_CONSULTOR
AS
	SELECT *
	FROM CONSULTORES 
	WHERE ELIMINADO = 'No'
GO

EXEC SP_LISTAR_CONSULTOR
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_CONSULTOR_FILTRO
(@dato varchar(50))
AS
	SELECT *
	FROM CONSULTORES
	WHERE (NOMBRE LIKE CONCAT(@dato,'%') OR APELLIDO LIKE CONCAT(@dato,'%') OR DNI LIKE CONCAT(@dato,'%')) AND ELIMINADO = 'No'
GO

CREATE OR ALTER PROCEDURE SP_ELIMINAR_CONSULTOR
(
@CODCONSUL CHAR(7)
)
AS
	UPDATE CONSULTORES SET ELIMINADO = 'Si' WHERE COD_CONSULTORES = @CODCONSUL
GO

/**************************FIN DE LOS PROCEDURES DE GESTION DE LOS CONSULTORES*************************************/


/*********************************INICIO DE LOS PROCEDURES DE GESTION DE LOS CLIENTES************************************/
CREATE OR ALTER PROCEDURE SP_LISTAR_TIPO_CLIENTE
AS
	SELECT *
	FROM TIPO_CLIENTE
GO

exec SP_LISTAR_CONSULTOR
GO

CREATE OR ALTER PROCEDURE SP_REGISTRAR_CLIENTE
(
@NOMCOM VARCHAR(100),
@DNIRUC CHAR(11),
@DIR VARCHAR(50),
@COR VARCHAR(50),
@TIPCLI INT
)
AS
	DECLARE @CODCLI CHAR(8)
	SET @CODCLI = 'CLI' + RIGHT('00000' + CAST(ISNULL((SELECT MAX(RIGHT(COD_CLIENTE,5)) FROM CLIENTE),0) +1 AS VARCHAR(5)), 5);

	INSERT INTO CLIENTE VALUES (@CODCLI, @NOMCOM, @DNIRUC, @DIR, @COR, @TIPCLI, 'No');
GO

CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_CLIENTE
(
@NOMCOM VARCHAR(50),
@DNIRUC CHAR(11),
@DIR VARCHAR(50),
@COR VARCHAR(50),
@TIPCLI INT,
@CODCLI CHAR(8)
)
AS
	UPDATE CLIENTE SET NOMBRES_COMPLETOS = @NOMCOM, DNIRUC = @DNIRUC, DIRECCION = @DIR, CORREO = @COR, TIPOCLI = @TIPCLI WHERE COD_CLIENTE = @CODCLI
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_CLIENTE
AS
	SELECT *
	FROM CLIENTE
	WHERE ELIMINADO = 'No'
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_CLIENTE_FILTRO
(@dato varchar(100))
AS
	SELECT *
	FROM CLIENTE
	WHERE (NOMBRES_COMPLETOS LIKE CONCAT(@dato, '%') OR DNIRUC LIKE CONCAT(@dato, '%')) AND ELIMINADO = 'No'
GO

CREATE OR ALTER PROCEDURE SP_ELIMINAR_CLIENTE
(
@cod_cliente CHAR(8)
)
AS
	UPDATE CLIENTE SET ELIMINADO = 'SI' WHERE COD_CLIENTE = @cod_cliente
GO

/*************************************FIN DE LOS PROCEDURES DE GESTION DE CLIENTES************************/


/**********************************INICIO DE LOS PROCEDURES DE GESTION DE PRODUCTO, TIPO DE PRODUCTO Y ANIMALES*****************/

CREATE OR ALTER PROCEDURE SP_LISTAR_TIPO_PRODUCTO
AS
	SELECT *
	FROM TIPO_PRODUCTO
GO

exec SP_LISTAR_TIPO_PRODUCTO
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_ANIMALES
AS
	SELECT *
	FROM ANIMALES
GO

CREATE OR ALTER PROCEDURE SP_REGISTRAR_PRODUCTO
(
@DESCRIP VARCHAR(50),
@PRECIO DECIMAL(10, 2),
@STOCK INT,
@ANIMAL INT,
@TIPCOMI INT
)
AS
	DECLARE @CODPRO CHAR(7);
	SET @CODPRO = 'PR' + RIGHT('00000' + CAST(ISNULL((SELECT MAX(RIGHT(CODIGO,5)) FROM PRODUCTOS),0) +1 AS VARCHAR(5)),5);

	INSERT INTO PRODUCTOS VALUES (@CODPRO, @DESCRIP,@PRECIO, @STOCK, @ANIMAL, @TIPCOMI, 'No')
GO

CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_PRODUCTO
(
@DESCRIP VARCHAR(50),
@PRECIO DECIMAL(10, 2),
@STOCK INT,
@ANIMAL INT,
@TIPCOMI INT,
@COD CHAR(7)
)
AS
	UPDATE PRODUCTOS SET DESCRIPCION = @DESCRIP,PRECIO =@PRECIO, STOCK = @STOCK, ANIMAL = @ANIMAL, TIPOCOMI = @TIPCOMI
	WHERE CODIGO = @COD
GO

select * from dbo.PRODUCTOS
go

CREATE OR ALTER PROCEDURE SP_LISTAR_PRODUCTO
AS
	SELECT *
	FROM PRODUCTOS
	WHERE ELIMINADO = 'No'
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_PRODUCTO_FILTRO
(@dato varchar(50))
AS
	SELECT *
	FROM PRODUCTOS
	WHERE DESCRIPCION LIKE CONCAT(@dato, '%') AND ELIMINADO = 'No'
GO

exec SP_LISTAR_PRODUCTO
GO


CREATE OR ALTER PROCEDURE SP_ELIMINAR_PRODUCTO
(
@codigo CHAR(7)
)
AS
	UPDATE PRODUCTOS SET ELIMINADO = 'Si' WHERE CODIGO = @codigo
GO

exec SP_ELIMINAR_PRODUCTO 'PR00001'

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUCTOS' AND COLUMN_NAME = 'fotopro';
go

/*drop procedure buscarProducto
go

create or alter procedure buscarProducto
(
@buscar varchar(50)
)
as
begin
select p.CODIGO,a.NOM_ANIMAL,p.DESCRIPCION,p.PRECIO,p.fotopro from PRODUCTOS p inner join ANIMALES a on p.ANIMAL = a.COD_ANIMAL  where p.DESCRIPCION LIKE '%' + @buscar + '%' OR a.NOM_ANIMAL LIKE '%' + @buscar + '%';
end
go

exec buscarProducto 'G'
go*/

select * from dbo.PRODUCTOS
go

CREATE OR ALTER PROCEDURE SP_LISTAR_TIPO_VENTA
AS
	SELECT *
	FROM TIPO_VENTA
GO

create or alter procedure SP_GRABAR_BOL_VENTA
@TIPO INT,
@CODCLI CHAR(8),
@CODEMP CHAR(7),
@CODCONSUL CHAR(7)
AS

	DECLARE @COD_VEN CHAR(7)
	SET @COD_VEN = 'VET' + RIGHT('0000' + CAST(ISNULL((SELECT MAX(RIGHT(CODIGO_VENTA,4)) FROM BOL_VENTA),0) +1 AS VARCHAR(4)),4);
	
	INSERT INTO BOL_VENTA VALUES (@COD_VEN,GETDATE(),@tipo,@CODCLI,@CODEMP,@CODCONSUL,0,'No')
go

CREATE OR ALTER PROCEDURE SP_ANULAR_BOL_VENTA
@CODVEN CHAR(7)
AS
	UPDATE BOL_VENTA SET ANULADO = 'Si' WHERE CODIGO_VENTA = @CODVEN 
GO

EXEC SP_GRABAR_BOL_VENTA 1,'CLI00001','EMP0001','CON0001'
GO

SELECT * FROM BOL_VENTA
GO
SELECT * FROM DET_VENTA
GO

EXEC GRABAR_DETA_VENTA 'VET0001','PR00001',2
GO
EXEC GRABAR_DETA_VENTA 'VET0001','PR00002',3
GO

SELECT * FROM PRODUCTOS
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_VENTA
AS
	SELECT * 
	FROM BOL_VENTA
	WHERE ANULADO = 'No'
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_VENTA_FILTRO
(@filtro varchar(50))
AS
	SELECT * 
	FROM BOL_VENTA
	WHERE (CODIGO_VENTA LIKE CONCAT(@filtro,'%') OR
	COD_CLIENTE LIKE CONCAT(@filtro,'%') OR 
	COD_EMPLEADO LIKE CONCAT(@filtro,'%')) AND ANULADO = 'No'
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_DETA_VENTA
AS
	SELECT * 
	FROM DET_VENTA
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_DETA_VENTA_FILTRO
(@filtro varchar(50))
AS
	SELECT * 
	FROM DET_VENTA
	WHERE CODVEN LIKE CONCAT(@filtro,'%') OR CODPROD LIKE CONCAT(@filtro,'%')
GO

create or alter procedure SP_GRABAR_DETA_VENTA
@COD_VEN CHAR(7),
@CODPROD CHAR(7), 
@CANTIDAD INT
AS
BEGIN
	DECLARE @PRECIOTOTAL DECIMAL(10,2)
	DECLARE @PRECIOUNI DECIMAL(10,2)
	SELECT @PRECIOUNI = PRECIO FROM PRODUCTOS WHERE CODIGO = @CODPROD
	SET @PRECIOTOTAL = (@CANTIDAD * @PRECIOUNI)
	
	INSERT INTO DET_VENTA values (@COD_VEN,@CODPROD,@CANTIDAD,@PRECIOTOTAL)
	-- ACTUALIZANDO EL STOCK DEL PRODUCTO
	UPDATE PRODUCTOS SET STOCK=STOCK - @CANTIDAD 
	WHERE CODIGO = @CODPROD
	
	DECLARE @TOTALSUMA DECIMAL(10,2)
	SELECT  @TOTALSUMA = SUM(PRECIO) FROM DET_VENTA WHERE CODVEN = @COD_VEN
	UPDATE BOL_VENTA SET TOTAL = @TOTALSUMA
	WHERE CODIGO_VENTA = @COD_VEN
END
GO


SELECT * FROM PRODUCTOS
GO

SELECT * FROM DBO.DET_VENTA
GO

select * from sys.procedures
go